add docker install from ci

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -74,22 +74,19 @@ jobs:
         uses: actions/checkout@v4
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - name: List files in the repository
+      - name: Install Docker if not present
         run: |
-          ls ${{ github.workspace }}
-          - name: Install Docker if not present
-          run: |
-            ssh production << 'EOF'
-              if ! command -v docker &> /dev/null; then
-                echo "Docker not found. Installing..."
-                curl -fsSL https://get.docker.com -o get-docker.sh
-                sh get-docker.sh
-                sudo usermod -aG docker $USER
-                echo "Docker installed successfully."
-              else
-                echo "Docker is already installed."
-              fi
-            EOF
+          ssh production << 'EOF'
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sh get-docker.sh
+              sudo usermod -aG docker $USER
+              echo "Docker installed successfully."
+            else
+              echo "Docker is already installed."
+            fi
+          EOF
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
